/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filosuvm;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author luisn
 */
public class Home extends java.awt.Frame {
    public static Movie movie;
    ArrayList <Movie> movies;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        User userLogin = Login.userLogin;
        String typeUser = userLogin.getType();  
        System.out.println(typeUser);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        btnClose.setCursor(new Cursor(HAND_CURSOR));
        getMovies();
        
        switch(typeUser){
            case "gerente":
                btnMovie.setVisible(true);
                btnCandy.setVisible(true);
                btnRegister.setVisible(true);
                btnReport.setVisible(true);
                break;
            case "tienda":
                btnMovie.setVisible(false);
                btnCandy.setVisible(true);
                btnRegister.setVisible(false);
                btnReport.setVisible(false);
                break;
            case "cajero":
                btnMovie.setVisible(true);
                btnCandy.setVisible(false);
                btnRegister.setVisible(false);
                btnReport.setVisible(false);
                break;
            default:
                btnMovie.setVisible(false);
                btnCandy.setVisible(false);
                btnRegister.setVisible(false);
                btnReport.setVisible(false);
        }
        
        
        pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        pnlRoot = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        pnlSide = new javax.swing.JPanel();
        Reports = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        Movies = new javax.swing.JPanel();
        btnMovie = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        pnlCandy = new javax.swing.JPanel();
        btnCandy = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        MoviePanel = new javax.swing.JPanel();
        bntMovie1 = new javax.swing.JButton();
        bntMovie2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        CandyPanel = new javax.swing.JPanel();
        ReportPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        jButton7.setText("jButton7");

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pnlRoot.setPreferredSize(new java.awt.Dimension(1500, 1080));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(28, 34, 43));
        Header.setPreferredSize(new java.awt.Dimension(100, 60));
        Header.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(28, 34, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(28, 34, 43));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/delete_32px.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 60));

        Header.add(jPanel1, java.awt.BorderLayout.LINE_END);

        pnlRoot.add(Header, java.awt.BorderLayout.PAGE_START);

        pnlSide.setBackground(new java.awt.Color(246, 19, 64));
        pnlSide.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports.setBackground(new java.awt.Color(246, 19, 64));
        Reports.setLayout(new java.awt.BorderLayout());

        btnReport.setBackground(new java.awt.Color(246, 19, 64));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/notas.png"))); // NOI18N
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        Reports.add(btnReport, java.awt.BorderLayout.CENTER);

        pnlSide.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 300, 140));

        Movies.setBackground(new java.awt.Color(246, 19, 64));
        Movies.setLayout(new java.awt.BorderLayout());

        btnMovie.setBackground(new java.awt.Color(246, 19, 64));
        btnMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/claqueta.png"))); // NOI18N
        btnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieActionPerformed(evt);
            }
        });
        Movies.add(btnMovie, java.awt.BorderLayout.CENTER);

        pnlSide.add(Movies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 140));

        jPanel7.setBackground(new java.awt.Color(246, 19, 64));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnRegister.setBackground(new java.awt.Color(246, 19, 64));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/inmigracion.png"))); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel7.add(btnRegister, java.awt.BorderLayout.CENTER);

        pnlSide.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 140));

        pnlCandy.setBackground(new java.awt.Color(246, 19, 64));
        pnlCandy.setLayout(new java.awt.BorderLayout());

        btnCandy.setBackground(new java.awt.Color(246, 19, 64));
        btnCandy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/palomitas-de-maiz.png"))); // NOI18N
        btnCandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandyActionPerformed(evt);
            }
        });
        pnlCandy.add(btnCandy, java.awt.BorderLayout.CENTER);

        pnlSide.add(pnlCandy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 140));

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MoviePanel.setBackground(new java.awt.Color(255, 255, 255));
        MoviePanel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        bntMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMovie1ActionPerformed(evt);
            }
        });
        MoviePanel.add(bntMovie1);

        bntMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMovie2ActionPerformed(evt);
            }
        });
        MoviePanel.add(bntMovie2);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton12);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton11);

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton15);

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton13);

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton14);

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton16);

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        MoviePanel.add(jButton17);

        pnlContent.add(MoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 1020));

        CandyPanel.setBackground(new java.awt.Color(204, 255, 153));
        pnlContent.add(CandyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 1020));

        ReportPanel.setBackground(new java.awt.Color(0, 102, 255));
        pnlContent.add(ReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 1020));

        jPanel11.setBackground(new java.awt.Color(102, 255, 102));
        pnlContent.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 1020));

        pnlRoot.add(pnlContent, java.awt.BorderLayout.CENTER);

        add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void getMovies(){
        
        ConnectionDB conn = new ConnectionDB();
        movies = conn.getMovies();
        
        String []list = {
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img1.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img2.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img3.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img4.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img5.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img6.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img7.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img8.jpg",
            "C:\\Users\\luisn\\Documents\\NetBeansProjects\\FilOSUvm\\src\\peliculas\\img9.jpg",
            
        };

        
        //Put all the images in the Buttons
        for(int i =0; i<list.length;i++){
               reziseImage(list[i],i);
        }
        
         
    }
    
    
    public void reziseImage(String src,int index){
        Component []components = MoviePanel.getComponents();
        ImageIcon icon = new ImageIcon(new ImageIcon(src).getImage().getScaledInstance(bntMovie1.getWidth(),bntMovie1.getHeight(), Image.SCALE_SMOOTH));
        if(components[index] instanceof JButton){
            JButton button = (JButton) components[index];
            button.setIcon(icon);
        }
    }
    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieActionPerformed
        MoviePanel.setVisible(true);
        CandyPanel.setVisible(false);
        jPanel11.setVisible(false);
        ReportPanel.setVisible(false);
    }//GEN-LAST:event_btnMovieActionPerformed

    private void btnCandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandyActionPerformed
        MoviePanel.setVisible(false);
        CandyPanel.setVisible(true);
        jPanel11.setVisible(false);
        ReportPanel.setVisible(false);
    }//GEN-LAST:event_btnCandyActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        MoviePanel.setVisible(false);
        CandyPanel.setVisible(false);
        jPanel11.setVisible(true);
        ReportPanel.setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        MoviePanel.setVisible(false);
        CandyPanel.setVisible(false);
        jPanel11.setVisible(false);
        ReportPanel.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void bntMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMovie1ActionPerformed
        movie = movies.get(0);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_bntMovie1ActionPerformed

    private void bntMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMovie2ActionPerformed
        movie = movies.get(1);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_bntMovie2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        movie = movies.get(2);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        movie = movies.get(3);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        movie = movies.get(4);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        movie = movies.get(5);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        movie = movies.get(6);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        movie = movies.get(7);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        movie = movies.get(8);
        Movies newWindow = new Movies();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CandyPanel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel MoviePanel;
    private javax.swing.JPanel Movies;
    private javax.swing.JPanel ReportPanel;
    private javax.swing.JPanel Reports;
    private javax.swing.JButton bntMovie1;
    private javax.swing.JButton bntMovie2;
    private javax.swing.JButton btnCandy;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMovie;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pnlCandy;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
