/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filosuvm;

import javax.swing.JFrame;

/**
 *
 * @author luisn
 */
public class Home extends java.awt.Frame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pnlRoot.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(28, 34, 43));
        Header.setPreferredSize(new java.awt.Dimension(100, 60));
        pnlRoot.add(Header, java.awt.BorderLayout.PAGE_START);

        pnlSide.setBackground(new java.awt.Color(246, 19, 64));
        pnlSide.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoot.add(pnlContent, java.awt.BorderLayout.CENTER);

        add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
