/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filosuvm;

import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author luisn
 */
public class Login extends java.awt.Frame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        maximize.setCursor(new Cursor(HAND_CURSOR));
        close.setCursor(new Cursor(HAND_CURSOR));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        iconstoolbar = new javax.swing.JPanel();
        btnMaxim = new javax.swing.JPanel();
        maximize = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlSidee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setName(""); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(28, 34, 43));
        pnlHeader.setPreferredSize(new java.awt.Dimension(100, 60));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        iconstoolbar.setBackground(new java.awt.Color(28, 34, 43));
        iconstoolbar.setPreferredSize(new java.awt.Dimension(200, 100));
        iconstoolbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaxim.setBackground(new java.awt.Color(28, 34, 43));
        btnMaxim.setLayout(new java.awt.BorderLayout());

        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/full_screen_32px.png"))); // NOI18N
        maximize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maximizeFocusGained(evt);
            }
        });
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
        });
        btnMaxim.add(maximize, java.awt.BorderLayout.CENTER);

        iconstoolbar.add(btnMaxim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 60));

        btnClose.setBackground(new java.awt.Color(28, 34, 43));
        btnClose.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(28, 34, 43));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/delete_32px.png"))); // NOI18N
        close.setBorder(null);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        btnClose.add(close, java.awt.BorderLayout.CENTER);

        iconstoolbar.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 60));

        pnlHeader.add(iconstoolbar, java.awt.BorderLayout.LINE_END);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   FilmOSUvm");
        pnlHeader.add(jLabel2, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlSidee.setBackground(new java.awt.Color(28, 34, 43));
        pnlSidee.setPreferredSize(new java.awt.Dimension(800, 100));
        pnlSidee.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/cinefondo.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnlSidee.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlSidee, java.awt.BorderLayout.WEST);

        pnlContent.setBackground(new java.awt.Color(246, 19, 64));
        pnlContent.setLayout(new java.awt.BorderLayout());

        pnlLogin.setBackground(new java.awt.Color(246, 19, 64));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        pnlLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        pnlLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(null);
        txtUser.setOpaque(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pnlLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 560, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filosuvm/icons/icons8-user-64.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(64, 64));
        pnlLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));
        pnlLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 560, 10));
        pnlLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 570, 10));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        pnlLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 570, 30));

        btnLogin.setBackground(new java.awt.Color(28, 34, 43));
        btnLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesion");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, 590, 60));

        pnlContent.add(pnlLogin, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlContent, java.awt.BorderLayout.CENTER);

        add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        
    }//GEN-LAST:event_maximizeMouseClicked

    private void maximizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maximizeFocusGained
       
    }//GEN-LAST:event_maximizeFocusGained

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    try{
       String emptyString= "";
       String user = txtUser.getText();
       char[] password = txtPassword.getPassword();
       Encode md5 = new Encode();
       String passE = md5.encode("1234");
       User gerente = new User("Sebastian Gonzalez",passE);
       String passD = gerente.getPassword();
       String passGerente = md5.decode(passD);
       
       if(emptyString.equals("") && emptyString.equals(new  String(password)) ){
            JOptionPane.showMessageDialog(null,"Los campos son obligatorios");
       }else{
           if(passGerente.equals(new String(password))){
                Home v1 = new Home();
                v1.setVisible(true);
                this.setVisible(false);
           }else{
               JOptionPane.showMessageDialog(null,"La contraseña o el usuario es incorrecto");
           }
       }
       
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel btnMaxim;
    private javax.swing.JButton close;
    private javax.swing.JPanel iconstoolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel maximize;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSidee;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
