/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filosuvm;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author luisn
 */
public class Movies extends java.awt.Frame {

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setInfoMovie();
    }
    
    
    public void setInfoMovie(){
        Movie movie = Home.movie;
        lblTitle.setText(movie.getName());
        ImageIcon icon = new ImageIcon(new ImageIcon(movie.getImage()).getImage().getScaledInstance(lblImage.getWidth(),lblImage.getHeight(), Image.SCALE_SMOOTH));
        lblImage.setIcon(icon);
        txtDescription.setEditable(false);
        txtDescription.setText(movie.getDescription());
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        BuyInfo = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Description = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(28, 34, 43));
        Header.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.add(Header, java.awt.BorderLayout.PAGE_START);

        BuyInfo.setBackground(new java.awt.Color(246, 19, 64));
        BuyInfo.setPreferredSize(new java.awt.Dimension(600, 100));
        BuyInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setPreferredSize(new java.awt.Dimension(600, 1020));
        BuyInfo.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 450, 440));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Titulo");
        BuyInfo.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 410, -1));

        txtDescription.setBackground(new java.awt.Color(246, 19, 64));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setBorder(null);
        jScrollPane2.setViewportView(txtDescription);

        BuyInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, 460, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descripcion");
        BuyInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 640, 450, -1));

        jPanel1.add(BuyInfo, java.awt.BorderLayout.WEST);

        Description.setMinimumSize(new java.awt.Dimension(400, 10));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Description.add(jButton1);

        jPanel1.add(Description, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Home newWindow = new Home();
          newWindow.setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyInfo;
    private javax.swing.JPanel Description;
    private javax.swing.JPanel Header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
